apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: integrator
  namespace: integrator
spec:
  $patch: delete
  hosts:
    - integrator.domain.com
    - 'integrator.$(CLUSTER_NAME).com'
